week 45 rails/goal-setter-master/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :checkpoints, except: [:show, :index, :new]

  resources :user_comments, only: [:create, :destroy]
end

week 45 rails/goal-setter-master/app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base
  validates :user_id, :title, presence: true
  validates :viewable, inclusion: { in: ['public', 'private'] }
  belongs_to :user
end

week 45 rails/goal-setter-master/app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :author_id, :checkpoint_id, :body, presence: true
  belongs_to :checkpoint
  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
  )
end

week 45 rails/goal-setter-master/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :checkpoints
  has_many(:comments, class_name: 'UserComment', foreign_key: :user_id, primary_key: :id)
  has_many(:self_comments, class_name: 'UserComment', foreign_key: :author_id, primary_key: :id)
  has_many(:goal_comments, class_name: 'GoalComment', foreign_key: :author_id, primary_key: :id)

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def correct_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user && user.correct_password?(password)
      return user
    end
    nil
  end
end

week 45 rails/goal-setter-master/app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :author_id, :body, :user_id, presence: true
  belongs_to( :author, class_name: 'User', foreign_key: :author_id, primary_key: :id)
  belongs_to :user
end

week 45 rails/goal-setter-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    session[:session_token] = user.session_token
  end

  def sign_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def signed_in?
    !!current_user
  end

  def must_log_in
    if !signed_in?
      flash[:errors] = ["Must Log In"]
      redirect_to new_session_url
    end
  end

  helper_method :current_user
  helper_method :signed_in?
end

week 45 rails/goal-setter-master/app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  before_action :must_log_in
  def create
    @checkpoint = Checkpoint.new(checkpoint_params)
    @checkpoint.user_id = current_user.id
    unless @checkpoint.save
      flash[:errors] = @checkpoint.errors.full_messages
    end
    redirect_to user_url(current_user)
  end

  def edit
    @checkpoint = Checkpoint.find(params[:id])
  end

  def update
    @checkpoint = Checkpoint.find(params[:id])
    if @checkpoint.update(checkpoint_params)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @checkpoint.errors.full_messages
      render :edit
    end
  end

  def destroy
    @checkpoint = Checkpoint.find(params[:id])
    @checkpoint.destroy
    redirect_to user_url(current_user)
  end

  private
  def checkpoint_params
    params.require(:checkpoint).permit(:title, :viewable)
  end
end

week 45 rails/goal-setter-master/app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController
end

week 45 rails/goal-setter-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
      if @user
        sign_in(@user)
        redirect_to users_url
      else
        flash.now[:errors] = ["Invalid sign in information"]
        render :new
      end
    end

    def destroy
      sign_out
      redirect_to new_session_url
    end

    private
    def user_params
      params.require(:user).permit(:username, :password)
    end

end

week 45 rails/goal-setter-master/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  def create
    @user_comment = UserComment.new(user_comment_params)
    @user_comment.author_id = current_user.id
    unless @user_comment.save
      flash[:errors] = @user_comment.errors.full_messages
    end
    redirect_to user_url(current_user)
  end

  def destroy
    @user_comment = UserComment.find(params[:id])
    @user_comment.destroy
    redirect_to user_url(current_user)
  end

  private
  def user_comment_params
    params.require(:user_comment).permit(:body, :user_id)
  end

end

week 45 rails/goal-setter-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_log_in, only: [:show, :index]


  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @public_goals = @user.checkpoints.select { |goal| goal.viewable == "public" }
    @private_goals = @user.checkpoints.select { |goal| goal.viewable == "private" }
    @user_id = params[:id]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

week 45 rails/goal-setter-master/app/helpers/application_helper.rb
module ApplicationHelper
end

week 45 rails/goal-setter-master/app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

week 45 rails/goal-setter-master/app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

week 45 rails/goal-setter-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

week 45 rails/goal-setter-master/app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

week 45 rails/goal-setter-master/app/helpers/users_helper.rb
module UsersHelper
end

week 45 rails/goal-setter-master/app/views/checkpoints/edit.html.erb
<h1> Edit Goal </h1>

<form action= "<%= checkpoint_url(@checkpoint) %>" method="post">
  <input type="hidden" name="authenticity_token" value= "<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value = "patch">
  <label>Title
    <input type="text" name="checkpoint[title]" value= "">
  </label>

  <label>viewable
    <select name="checkpoint[viewable]">
      <option value="public">Public</option>
      <option value="private">Private</option>
    </select>
  </label>
  <br>
  <input type="submit" value="Edit Goal">

week 45 rails/goal-setter-master/app/views/users/index.html.erb
<h1>All Users</h1>
<ul><% @users.each do |user| %>
    <li><%=link_to user.username, user_url(user) %></li>
  <% end %>
</ul>

week 45 rails/goal-setter-master/app/views/users/new.html.erb
<h1> Sign Up </h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>"
  >
  <label>Username
    <input type="text" name="user[username]" value="<%=@user.username%>">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" value="Sign Up">

week 45 rails/goal-setter-master/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>
<%= render 'user_comments/comments', comments: @user.comments, user_id: @user_id %>

<% if @public_goals.empty? %>
  <ul>No Goals</ul>
<% else %>
  <ul>
    <% @public_goals.each do |p_goal| %>
      <li><%= p_goal.title %>
          <% if current_user == @user %>
            <%= button_to "Destroy Goal", checkpoint_url(p_goal), method: :delete %>
            <%= button_to "Edit Goal", edit_checkpoint_url(p_goal), method: :get %>
          <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<% if current_user == @user %>
    <ul>
      <% @private_goals.each do |p_goal| %>
        <li> <%= p_goal.title %>
            <%= button_to "Destroy Goal", checkpoint_url(p_goal), method: :delete %>
            <%= button_to "Edit Goal", edit_checkpoint_url(p_goal), method: :get %>
        </li>
      <% end %>
    </ul>
    <hr>
    <h2>Add a Goal</h2>
    <br>
    <form action="<%=checkpoints_url%>" method="post">
      <input type="hidden" name="authenticity_token" value= "<%= form_authenticity_token %>">
      <label>Title
        <input type="text" name="checkpoint[title]" value= "">
      </label>

      <label>viewable
        <select name="checkpoint[viewable]">
          <option value="public">Public</option>
          <option value="private">Private</option>
        </select>
      </label>
      <br>
      <input type="submit" value="Add Goal">
    </form>
<% end %>