week 45 rails/reddit-clone-master/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users, except: [:edit, :update]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy
  resources :posts, except: [:destroy, :index]
  resources :comments, only: [:new, :create]
end

week 45 rails/reddit-clone-master/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  # validate :has_at_least_one_sub
  has_many :comments, as: :commentable

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :post_subs,
    class_name: 'PostSub',
    foreign_key: :post_id,
    primary_key: :id

  )

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )


  def has_at_least_one_sub
    if self.post_subs.nil?
      errors.add(:no_associated_subs, "A post must be linked to at least one sub!")
    end
  end
end

week 45 rails/reddit-clone-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :logged_in?
  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    if params[:post][:subs] == []
      flash.now[:errors] = ['You must select at least one sub']
      render :new
      return
    end
    if @post.save
      post_subs = params[:post][:subs]
      post_subs.each do |post_sub_id|
        PostSub.create(post_id: @post.id, sub_id: post_sub_id.to_i )
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    @subs = Sub.all
    if params[:post][:subs].nil? || params[:post][:subs].empty?
      flash.now[:errors] = ['You must select at least one sub']
      render :edit
      return
    end
    post_subs = @post.post_subs.map { |ps| ps.sub_id }
    new_post_subs = params[:post][:subs].map { |ps| ps.to_i }
    create_post_subs = new_post_subs - post_subs
    delete_post_subs = post_subs - new_post_subs
    if @post.update(post_params)
      delete_post_subs.each do |sub_id|
        PostSub.find_by(post_id: @post.id, sub_id: sub_id).destroy
      end
      create_post_subs.each do |sub_id|
        PostSub.create(post_id: @post.id, sub_id: sub_id)
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    #@all_comments = Comment.where() where post id = the current post, then we want to do the iteration to eliminate n+1 queries
  end

  def correct_user
    @post = Post.find(params[:id])
    redirect_to subs_url if current_user != @post.author
  end
  private

    def post_params
      params.require(:post).permit(:title, :url, :content, :author_id, :subs)
    end


end

week 45 rails/reddit-clone-master/app/helpers/posts_helper.rb
module PostsHelper
end

week 45 rails/reddit-clone-master/app/views/posts/_form.html.erb
<!-- <h1 <%#= sub.title %> </h1> -->
<h2> <%= post_action %> a post </h2>
<!-- We need post_action, action_url, button_name, method -->
<form action = "<%=  action_url %>" method = "post">
  <input type="hidden" name="_method" value = "<%= method %>">
  <input type="hidden" name = "authenticity_token" value = "<%= form_authenticity_token %>">
  <input type="hidden" name = "post[author_id]" value = "<%= current_user.id %>">
  <label>Post Title:
    <input type="text" name = "post[title]" value = "<%= post.title %>">
  </label>
  <br>
  <label>Post URL:
    <input type="text" name = "post[url]" value = "<%= post.url %>">
  </label>
  <br>
  <label>Post Content:
    <textarea  name = "post[content]"><%= post.content%></textarea>
  </label>
  <br>

  <% subs.each do |sub| %>

    <input type="checkbox" name="post[subs][]" id="post_sub_<%= sub.title %>" value="<%= sub.id %>"
      <%= 'checked' if post.subs.include?(sub) %>
    >
    <label for="post_sub_<%= sub.title %>"><%= sub.title %></label>
    <br>

  <% end %>

  <input type="submit" value = "<%= button_name %>">

  <br>
  <!-- <%#= link_to "Back to the sub!", sub_url(sub.id) %> -->

week 45 rails/reddit-clone-master/app/views/posts/edit.html.erb
<%= render 'form',
  post_action: "Edit",
  action_url: post_url(@post),
  post: @post,
  subs: @subs,
  method: 'patch',
  button_name: 'Update!' %>

week 45 rails/reddit-clone-master/app/views/posts/new.html.erb
<%= render 'form',
  post_action: "Create",
  action_url: posts_url,
  post: @post,
  method: 'post',
  button_name: 'Create!',
  subs: @subs
  %>

week 45 rails/reddit-clone-master/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<% @post.attributes.each do |key, value| %>

<ul>
  <li>
    <%= key.to_s + " is " + value.to_s %>
  </li>
</ul>
<% end %>
<br>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <ul>
    <li>
      <%= render 'comments/comments_comments', parent_comment: comment %>
    </li>
  </ul>
<% end %>
<br>


<ul>
<% @post.subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub.id)  %>
  </li>
</ul>
<% end %>

<%= button_to 'Edit Post', edit_post_url(@post), method: :get %>

<%= button_to 'Make a comment',
    new_comment_url,
    method: :get,
    params: {
      post_id: @post.id,
      source_type: @post.class.to_s,
      source_id: @post.id } %>